### ISSUE TITLE
setDonationUrl() crash

### ISSUE THREAD

**Issue by jakimfett** [jakimfett/Minechem#561]
Versions:
Forge 10.13.2.1277
CoFHCore v[1.7.10]3.0.0B9-71
Minechem v5.0.5 for 1.7.10, build 359

error:
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: minechem.Minechem.setDonationURL()
Caused by: java.lang.NoSuchMethodError: minechem.Minechem.setDonationURL()

Full [crash log](http://pastebin.com/PkCSdB3q)

**Comment by jakimfett** [comment]
Probably broken by https://github.com/jakimfett/Minechem/pull/560

**Comment by jakimfett** [comment]
@hilburn that fixed the NoSuchMethodError, but now it's throwing:
cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessException: Class cpw.mods.fml.common.ILanguageAdapter$JavaAdapter can not access a member of class minechem.Minechem with modifiers ""

Full [crash log](http://pastebin.com/9eiQnXuT)

**Comment by jakimfett** [comment]
Appears to be fixed, thanks @hilburn
